COMPILE_DEPS = CORE_DEPS + JACKSON + KRYO + REST + CLI

osgi_jar_with_tests(
	deps = COMPILE_DEPS,
)

onos_app(
	category = "Utility",
	description = "IFWD",
	title = "Sample Intent Reactive Forwarding",
	url = "http://onosproject.org",
)
