COMPILE_DEPS = CORE_DEPS + [
    "@snakeyaml//jar",
    #"@gson//:gson-api",
    "@com_google_code_gson_gson//jar",
    #"@jgrapht//:jgrapht-api",
    "@jgrapht_core//jar",
]
osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)
