BUNDLES = [
    "//apps/nifwd_combined/app:onos-apps-nifwd_combined-app",
    "@com_google_code_gson_gson//jar",
    #"@jgrapht//:jgrapht-api",
    "@jgrapht_core//jar",
    "@snakeyaml//jar",
]

onos_app(
    category = "Utility",
    included_bundles = BUNDLES,
    #required_apps = ["org.onosproject.hostprovider"],
    title = "Netviews Policy COMBINED",
    url = "http://onosproject.org",
)
